### ISSUE TITLE
Upgrade to rails 3.1

### ISSUE THREAD

**Issue by afcapel** [PartidoDeInternet/AgoraOnRails#38]
The rails upgrade in itself shouldn't be difficult. There is an railscast on how to acomplish this. 

http://railscasts.com/episodes/282-upgrading-to-rails-3-1?language=es&view=asciicast

At the moment, there's no need to use extended features of the asset pipeline.

**Comment by bglusman** [comment]
I started work on this, but am bumping up against some incompatibility in rails 3.1 with the tractis identity plugin...  I'll work on it a bit more, but since there's also a task to refactor to use omniauth with tractis as just an omni-auth strategy (I assume?), maybe that's a better approach and will solve at the same time?  I may switch to working on omniauth switchover but open to feedback

**Comment by afcapel** [comment]
Upgraded to 3.1 thanks to bglusman.

https://github.com/PartidoDeInternet/AgoraOnRails/pull/41
